### ISSUE TITLE
allow adding sidecars in helm values

### ISSUE THREAD

**Issue by stevenaldinger** [questdb/questdb-kubernetes#110]
My particular use case is for adding a volume monitoring sidecar for prometheus to scrape. I'll open a PR for this, I just wanted an issue to link to.

Example values:
```yaml
sidecars:
- name: volume-exporter
  image:  mnadeem/volume_exporter
  imagePullPolicy: "Always"
  args:
  - --volume-dir=questdb:/var/lib/questdb/db
  ports:
  - name: metrics-volume
    containerPort: 9888
  volumeMounts:
  - mountPath: /var/lib/questdb/db
    name: questdb
    readOnly: true
```
