### ISSUE TITLE
Disabling persistency does not create QuestDB pod

### ISSUE THREAD

**Issue by jphavoc** [questdb/questdb-kubernetes#28]
Installing Helm chart with the following command `kubectl install questdb questdb/questdb --values=values.yaml --debug --create-namespace --namespace benchmark`

using `values.yaml`:
```yaml
image:
  repository: questdb/questdb
  pullPolicy: IfNotPresent
  tag: 6.0.3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

questdb:
  config:
    enabled: true
    options:
      shared.worker.count: 8
      http.min.enabled: true
      telemetry.enabled: false
      line.tcp.max.uncommitted.rows: 1000
      line.tcp.maintenance.job.interval: 500
      line.tcp.timestamp: n

service:
  annotations: {}
  type: NodePort
  port: 9000
  expose:
    postgresql:
      enabled: false
      port: 8812
    influxdb:
      enabled: true
      port: 9009

persistence:
  enabled: fase
  accessMode: ReadWriteOnce
  size: 1Gi

ingress:
  enabled: false
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
```

Using `kubectl -n benchmark describe statefulset` gives

```
Name:               questdb
Namespace:          benchmark
CreationTimestamp:  Wed, 07 Jul 2021 13:43:16 +0200
Selector:           app.kubernetes.io/instance=questdb,app.kubernetes.io/name=questdb
Labels:             app.kubernetes.io/instance=questdb
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=questdb
                    app.kubernetes.io/version=6.0.3
                    helm.sh/chart=questdb-0.8.0
Annotations:        meta.helm.sh/release-name: questdb
                    meta.helm.sh/release-namespace: benchmark
Replicas:           1 desired | 0 total
Update Strategy:    RollingUpdate
  Partition:        0
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app.kubernetes.io/instance=questdb
           app.kubernetes.io/name=questdb
  Containers:
   questdb:
    Image:        questdb/questdb:6.0.3
    Ports:        9000/TCP, 8812/TCP, 9009/TCP
    Host Ports:   0/TCP, 0/TCP, 0/TCP
    Environment:  <none>
    Mounts:
      /root/.questdb/conf/server.conf from config (rw,path="server.conf")
      /root/.questdb/db from questdb (rw)
  Volumes:
   data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   config:
    Type:       ConfigMap (a volume populated by a ConfigMap)
    Name:       questdb
    Optional:   false
Volume Claims:  <none>
Events:
  Type     Reason        Age               From                    Message
  ----     ------        ----              ----                    -------
 Warning  FailedCreate  4s (x11 over 9s)  statefulset-controller  create Pod questdb-0 in StatefulSet questdb failed error: Pod "questdb-0" is invalid: spec.containers[0].volumeMounts[0].name: Not found: "questdb"
```
