### ISSUE TITLE
Missing ingressClassName property in Ingress.yaml

### ISSUE THREAD

**Issue by DeadP4xel** [questdb/questdb-kubernetes#50]
Hey,

During the implementation in my Kubernetes cluster I noticed that the property "ingressClassName" is missing in your Ingress.yaml template file. 

I need this for my NGINX ingress controller. Currently I set this property via Lens directly in my ingress. It would be nice if this would be set automatically by the helm config.

```
ingress:
  enabled: true
  annotations: {}
  tls:
    - hosts:
        - databasequestdb-my-domain.tld
  hosts:
    - host: databasequestdb-my-domain.tld
      paths:
        - /
  ingressClassName: nginx-1  #This is missing
```

Am I missing something?

Thank you in advance
