### ISSUE TITLE
Add extraVolumeMounts and extraVolumes for backup directory

### ISSUE THREAD

**Issue by DinGo4DEV** [questdb/questdb-kubernetes#98]
Please consider to add **extraVolumeMounts** and **extraVolumes** for external mount volumes on `values.yaml` and `templates/statefulset.yaml`

Installing helm chart using `values.yaml` :
``` yaml
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 50Gi
questdb:
  serverConfig:
    enabled: true
    options:
      cairo.sql.backup.root: /var/lib/questdb/backups
 ## skip irrelevant configure ...
```

`longhorn` is my default storage class which is distributed block storage, 

therefore I would like to store the backup directory to external volume which mount to other storage class such as `NFS` or `local` for more reliable and easier storage management.
